# Build
FROM node:lts AS build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci
COPY . .

# Production
FROM node:lts
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --only=production
COPY --from=build /usr/src/app ./app
EXPOSE 3000
CMD [ "npm", "start" ]
